# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
